# === 1. Set config parameters ===
name: "calpha_diffusion" # default name for the experiment
seed: 52 # seed for random number generators in pytorch, numpy and python.random
run_name: "calpha_diffusion"
num_workers: 4

vp_diffuser:
 _target_: src.diffusion.sde_diffusion.VPGraphSDE
 beta_min: 0.1
 beta_max: 20.0
 N: 1000

hoog_diffuser:
 _target_: src.diffusion.sde_diffusion.HoogeboomGraphSDE
 s: 1e-5
 clip_value: 0.25
 exponent: 2
 N: 500

se3_diffuser: 
  _target_: src.diffusion.so3_diffuser.SO3Diffuser
  diffuse_trans: True
  diffuse_rot: True
  r3_diffuser:
    _target_: src.diffusion.r3_diffuser.R3Diffuser
    min_b: 0.1
    max_b: 20.0
    coordinate_scaling: 0.1
  so3_diffuser:
    _target_: src.diffusion.so3_diffuser.SO3Diffuser
    num_omega: 1000
    num_sigma: 1000
    min_sigma: 0.1
    max_sigma: 1.5
    schedule: logarithmic
    cache_dir: .cache/



# === 2. Specify defaults here. Defaults will be overwritten by equivalently named options in this file ===
# defaults:
#   - optional env: default
#   - dataset: ec_reaction
  # - model: gvp_denoiser 
#   - logger: default
#   - callbacks: default
#   - optimiser: adam     # TODO: Add to training config
#   - trainer: default   # TODO: Update 
#   - sweeper: wandb
  